export const colors = {
    'fire':   '#FDDFDF', 
    'grass':  '#DEFDE0', 
    'electric':'#FCF7DE', 
    'water':  '#DEF3FD', 
    'ground': '#F4E7DA', 
    'rock':   '#D5D5D4', 
    'fairy':  '#FCEAFF', 
    'poison': '#98D7A5', 
    'bug':    '#F8D5A3', 
    'dragon': '#97B3E6', 
    'psychic':'#EAEDA1', 
    'flying':  '#518cee', 
    'fighting':'#E6E0D4', 
    'normal': '#F5F5F5',
    'red':    '#ef4444', 
    'white':  '#ffff',
    'black':  '#000',
}